function data = import_EKF_bin(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BROF1EKFLOG = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  BROF1EKFLOG = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  broF1EKFLog = importfile("D:\Kurser-MDH\Exjobb_FOI\DynamikModel\Data\PiRecorded\Data\bro_F1_EKF_Log.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Apr-2021 13:25:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 96);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["EKFTFlags", "EKFWeek", "EKFTOW", "Latx8201", "Lonx8201", "HtAbvEllipsx8201", "Flagsx8201", "LLHUCNx8208", "LLHUCEx8208", "LLHUCDx8208", "Flagsx8208", "VelNx8202", "VelEx8202", "VelDx8202", "Flagsx8202", "VelUCNx8209", "VelUCEx8209", "VelUCDx8209", "Flagsx8209", "RollUCx820A", "PitchUCx820A", "YawUCx820A", "Flagsx820A", "q0x8203", "q1x8203", "q2x8203", "q3x8203", "Flagsx8203", "XAccBiasx8207", "YAccBiasx8207", "ZAccBiasx8207", "Flagsx8207", "XAccBiasUCx820C", "YAccBiasUCx820C", "ZAccBiasUCx820C", "Flagsx820C", "XAccSFx8217", "YAccSFx8217", "ZAccSFx8217", "Flagsx8217", "XAccSFUCx8219", "YAccSFUCx8219", "ZAccSFUCx8219", "Flagsx8219", "XGyroBiasx8206", "YGyroBiasx8206", "ZGyroBiasx8206", "Flagsx8206", "XGyroBiasUCx820B", "YGyroBiasUCx820B", "ZGyroBiasUCx820B", "Flagsx820B", "XGyroSFx8216", "YGyroSFx8216", "ZGyroSFx8216", "Flagsx8216", "XGyroSFUCx8218", "YGyroSFUCx8218", "ZGyroSFUCx8218", "Flagsx8218", "WGS84Gravityx820F", "Flagsx820F", "IntenNx8215", "IntenEx8215", "IntenDx8215", "Inclx8215", "Declx8215", "Flagsx8215", "XMagAutoHardIronOffsetx8225", "YMagAutoHardIronOffsetx8225", "ZMagAutoHardIronOffsetx8225", "Flagsx8225", "XMagAutoHardIronOffsetUCx8228", "YMagAutoHardIronOffsetUCx8228", "ZMagAutoHardIronOffsetUCx8228", "Flagsx8228", "MagAutoSoftIronM11x8226", "MagAutoSoftIronM12x8226", "MagAutoSoftIronM13x8226", "MagAutoSoftIronM21x8226", "MagAutoSoftIronM22x8226", "MagAutoSoftIronM23x8226", "MagAutoSoftIronM31x8226", "MagAutoSoftIronM32x8226", "MagAutoSoftIronM33x8226", "Flagsx8226", "MagAutoSoftIronUCM11x8229", "MagAutoSoftIronUCM12x8229", "MagAutoSoftIronUCM13x8229", "MagAutoSoftIronUCM21x8229", "MagAutoSoftIronUCM22x8229", "MagAutoSoftIronUCM23x8229", "MagAutoSoftIronUCM31x8229", "MagAutoSoftIronUCM32x8229", "MagAutoSoftIronUCM33x8229", "Flagsx8229"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

end